import type { AppDefinition } from '../ir'

/**
 * Generates standalone, executable Figma Plugin JavaScript (code.js)
 * that translates an AppDefinition directly into native Figma nodes via the Figma Plugin API.
 */
export function generateFigmaPluginCode(appDef: AppDefinition): string {
  const jsonStr = JSON.stringify(appDef, null, 2)

  return `// Generated by React-to-Figma Rendering System
// App: ${appDef.name}
// Generated at: ${new Date().toISOString()}

const appDefinition = ${jsonStr};

function hexToRgb(h) {
  const clean = h.replace('#', '');
  if (clean.length === 3) {
    return {
      r: parseInt(clean[0] + clean[0], 16) / 255,
      g: parseInt(clean[1] + clean[1], 16) / 255,
      b: parseInt(clean[2] + clean[2], 16) / 255
    };
  }
  return {
    r: parseInt(clean.slice(0, 2), 16) / 255,
    g: parseInt(clean.slice(2, 4), 16) / 255,
    b: parseInt(clean.slice(4, 6), 16) / 255
  };
}

function toFigmaPaint(color) {
  if (!color) return [];
  if (typeof color === 'string') {
    return [{ type: 'SOLID', color: hexToRgb(color) }];
  }
  return [{
    type: 'SOLID',
    color: { r: color.r, g: color.g, b: color.b },
    opacity: color.a !== undefined ? color.a : 1
  }];
}

async function loadFonts() {
  const fonts = [
    { family: 'Inter', style: 'Regular' },
    { family: 'Inter', style: 'Medium' },
    { family: 'Inter', style: 'Semi Bold' },
    { family: 'Inter', style: 'Bold' },
    { family: 'Roboto', style: 'Regular' },
    { family: 'Roboto', style: 'Bold' }
  ];

  for (const f of fonts) {
    try {
      await figma.loadFontAsync(f);
    } catch (e) {}
  }
}

function applyLayout(node, layout) {
  if (!layout) {
    node.layoutMode = 'NONE';
    return;
  }

  if (layout.direction === 'vertical') {
    node.layoutMode = 'VERTICAL';
  } else if (layout.direction === 'horizontal') {
    node.layoutMode = 'HORIZONTAL';
  } else {
    node.layoutMode = 'NONE';
  }

  if (node.layoutMode !== 'NONE') {
    node.itemSpacing = layout.gap || 0;
    node.paddingTop = layout.paddingTop || 0;
    node.paddingRight = layout.paddingRight || 0;
    node.paddingBottom = layout.paddingBottom || 0;
    node.paddingLeft = layout.paddingLeft || 0;

    if (layout.alignItems === 'start') node.counterAxisAlignItems = 'MIN';
    else if (layout.alignItems === 'center') node.counterAxisAlignItems = 'CENTER';
    else if (layout.alignItems === 'end') node.counterAxisAlignItems = 'MAX';

    if (layout.justifyContent === 'start') node.primaryAxisAlignItems = 'MIN';
    else if (layout.justifyContent === 'center') node.primaryAxisAlignItems = 'CENTER';
    else if (layout.justifyContent === 'end') node.primaryAxisAlignItems = 'MAX';
    else if (layout.justifyContent === 'space-between') node.primaryAxisAlignItems = 'SPACE_BETWEEN';

    if (layout.width === 'fill') {
      try { node.layoutSizingHorizontal = 'FILL'; node.layoutGrow = 1; } catch (e) {}
    } else if (layout.width === 'hug') {
      try { node.layoutSizingHorizontal = 'HUG'; } catch (e) {}
    } else if (typeof layout.width === 'number') {
      node.resize(layout.width, node.height || 40);
    }

    if (layout.height === 'fill') {
      try { node.layoutSizingVertical = 'FILL'; } catch (e) {}
    } else if (layout.height === 'hug') {
      try { node.layoutSizingVertical = 'HUG'; } catch (e) {}
    } else if (typeof layout.height === 'number') {
      node.resize(node.width || 40, layout.height);
    }
  } else {
    const w = typeof layout.width === 'number' ? layout.width : node.width;
    const h = typeof layout.height === 'number' ? layout.height : node.height;
    node.resize(w, h);
  }
}

function applyStyle(node, style) {
  if (!style) return;
  if (style.fill) node.fills = toFigmaPaint(style.fill);
  if (style.stroke) {
    node.strokes = toFigmaPaint(style.stroke);
    node.strokeWeight = style.strokeWidth || 1;
  }
  if (style.cornerRadius !== undefined) {
    node.cornerRadius = Array.isArray(style.cornerRadius) ? style.cornerRadius[0] : style.cornerRadius;
  }
  if (style.opacity !== undefined) node.opacity = style.opacity;
}

const componentRegistry = new Map();
const screenRegistry = new Map();
const interactiveNodes = [];

async function renderIRNode(ir) {
  let figmaNode;

  switch (ir.type) {
    case 'frame': {
      const f = figma.createFrame();
      f.name = ir.name || 'Frame';
      applyLayout(f, ir.layout);
      applyStyle(f, ir.style);

      if (ir.children) {
        for (const childIR of ir.children) {
          const childNode = await renderIRNode(childIR);
          f.appendChild(childNode);
        }
      }
      figmaNode = f;
      break;
    }

    case 'text': {
      const t = figma.createText();
      t.name = ir.name || ir.content.slice(0, 20);
      try {
        const style = ir.style && (ir.style.fontWeight === 'bold' || ir.style.fontWeight >= 700) ? 'Bold' : 'Regular';
        t.fontName = { family: 'Inter', style };
      } catch (e) {
        t.fontName = { family: 'Roboto', style: 'Regular' };
      }
      t.characters = ir.content || '';
      if (ir.style && ir.style.fontSize) t.fontSize = ir.style.fontSize;
      if (ir.style && ir.style.color) t.fills = toFigmaPaint(ir.style.color);
      figmaNode = t;
      break;
    }

    case 'rectangle': {
      const r = figma.createRectangle();
      r.name = ir.name || 'Rectangle';
      const w = typeof ir.width === 'number' ? ir.width : 100;
      const h = typeof ir.height === 'number' ? ir.height : 100;
      r.resize(w, h);
      applyStyle(r, ir.style);
      figmaNode = r;
      break;
    }

    case 'component': {
      const c = figma.createComponent();
      c.name = ir.name || ir.componentName;
      applyLayout(c, ir.layout);
      applyStyle(c, ir.style);
      if (ir.children) {
        for (const childIR of ir.children) {
          const child = await renderIRNode(childIR);
          c.appendChild(child);
        }
      }
      componentRegistry.set(ir.componentName, c);
      figmaNode = c;
      break;
    }

    case 'instance': {
      const mainComp = componentRegistry.get(ir.componentName);
      if (mainComp) {
        const inst = mainComp.createInstance();
        inst.name = ir.name || mainComp.name;
        if (ir.layout) applyLayout(inst, ir.layout);
        if (ir.overrides && ir.overrides.style) applyStyle(inst, ir.overrides.style);
        figmaNode = inst;
      } else {
        const placeholder = figma.createFrame();
        placeholder.name = ir.name || ir.componentName;
        applyLayout(placeholder, ir.layout);
        figmaNode = placeholder;
      }
      break;
    }
  }

  if (ir.interaction && figmaNode) {
    interactiveNodes.push({ node: figmaNode, interaction: ir.interaction, name: ir.name });
  }

  return figmaNode;
}

async function run() {
  await loadFonts();

  const page = figma.createPage();
  page.name = appDefinition.name;

  // 1. Render reusable components
  if (appDefinition.components) {
    let cx = 0;
    for (const compIR of appDefinition.components) {
      const c = await renderIRNode(compIR);
      c.x = cx;
      c.y = -220;
      page.appendChild(c);
      cx += c.width + 40;
    }
  }

  // 2. Render screens
  const screenFrames = [];
  let sx = 0;
  for (const screenDef of appDefinition.screens) {
    const screenFrame = await renderIRNode(screenDef.root);
    screenFrame.name = screenDef.name;
    screenFrame.x = sx;
    screenFrame.y = 0;
    page.appendChild(screenFrame);

    screenRegistry.set(screenDef.id.toLowerCase(), screenFrame);
    screenRegistry.set(screenDef.name.toLowerCase(), screenFrame);
    screenFrames.push(screenFrame);
    sx += screenFrame.width + 120;
  }

  // 3. Resolve Prototype Connections (Phase 7 & 8)
  for (const item of interactiveNodes) {
    if (item.interaction && item.interaction.destination) {
      const dest = screenRegistry.get(item.interaction.destination.toLowerCase());
      if (dest) {
        try {
          item.node.reactions = [{
            trigger: { type: item.interaction.trigger === 'hover' ? 'ON_HOVER' : 'ON_CLICK' },
            action: {
              type: 'NODE',
              destinationId: dest.id,
              navigation: item.interaction.action === 'open-overlay' ? 'OVERLAY' : 'NAVIGATE',
              transition: {
                type: item.interaction.transition === 'instant' ? 'INSTANT' : 'SMART_ANIMATE',
                duration: 0.3,
                easing: { type: 'EASE_IN_AND_OUT' }
              }
            }
          }];
        } catch (e) {
          console.warn('Could not set reactions on node:', item.name, e);
        }
      }
    }
  }

  figma.currentPage = page;
  figma.viewport.scrollAndZoomIntoView(screenFrames);
  figma.closePlugin('Generated ' + screenFrames.length + ' screens with editable Auto Layout and prototype connections');
}

run().catch((e) => {
  figma.closePlugin('Error: ' + ((e && e.message) || String(e)));
});
`
}
