// Generated by React-to-Figma Rendering System
// App: Wisal Chat App • React to Figma
// Generated at: 2026-09-16T10:26:00.721Z

const appDefinition = {
  "name": "Wisal Chat App • React to Figma",
  "components": [
    {
      "type": "component",
      "name": "Button",
      "componentName": "Button",
      "layout": {
        "direction": "horizontal",
        "gap": 8,
        "paddingTop": 12,
        "paddingBottom": 12,
        "paddingLeft": 24,
        "paddingRight": 24,
        "alignItems": "center",
        "justifyContent": "center"
      },
      "style": {
        "fill": {
          "r": 0.11372549019607843,
          "g": 0.6078431372549019,
          "b": 0.9411764705882353,
          "a": 1
        },
        "cornerRadius": 10
      },
      "children": [
        {
          "type": "text",
          "name": "label",
          "content": "Button",
          "style": {
            "fontSize": 15,
            "fontWeight": "semibold",
            "color": {
              "r": 1,
              "g": 1,
              "b": 1,
              "a": 1
            },
            "textAlign": "center"
          }
        }
      ]
    }
  ],
  "screens": [
    {
      "id": "Login",
      "name": "Login Screen",
      "root": {
        "type": "frame",
        "id": "Login",
        "name": "Login",
        "layout": {
          "direction": "vertical",
          "paddingTop": 32,
          "paddingRight": 32,
          "paddingBottom": 32,
          "paddingLeft": 32,
          "justifyContent": "space-between",
          "width": 390,
          "height": 844
        },
        "style": {
          "fill": {
            "r": 0.0392156862745098,
            "g": 0.047058823529411764,
            "b": 0.058823529411764705,
            "a": 1
          }
        },
        "children": [
          {
            "type": "frame",
            "name": "Stack",
            "layout": {
              "direction": "vertical",
              "gap": 24,
              "width": "fill"
            },
            "style": {},
            "children": [
              {
                "type": "frame",
                "name": "Row",
                "layout": {
                  "direction": "horizontal",
                  "gap": 12,
                  "alignItems": "center"
                },
                "style": {},
                "children": [
                  {
                    "type": "rectangle",
                    "name": "Rectangle",
                    "width": 40,
                    "height": 40,
                    "style": {
                      "fill": {
                        "r": 0.11372549019607843,
                        "g": 0.6078431372549019,
                        "b": 0.9411764705882353,
                        "a": 1
                      },
                      "cornerRadius": 10
                    }
                  },
                  {
                    "type": "text",
                    "name": "Wisal",
                    "content": "Wisal",
                    "style": {
                      "fontSize": 22,
                      "fontWeight": "bold",
                      "color": {
                        "r": 1,
                        "g": 1,
                        "b": 1,
                        "a": 1
                      }
                    }
                  }
                ]
              },
              {
                "type": "frame",
                "name": "Stack",
                "layout": {
                  "direction": "vertical",
                  "gap": 8,
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "text",
                    "name": "Welcome back",
                    "content": "Welcome back",
                    "style": {
                      "fontSize": 32,
                      "fontWeight": "bold",
                      "color": {
                        "r": 1,
                        "g": 1,
                        "b": 1,
                        "a": 1
                      }
                    }
                  },
                  {
                    "type": "text",
                    "name": "Enter your credentials t",
                    "content": "Enter your credentials to access your secure chat workspace.",
                    "style": {
                      "fontSize": 15,
                      "color": {
                        "r": 0.5803921568627451,
                        "g": 0.6392156862745098,
                        "b": 0.7215686274509804,
                        "a": 1
                      }
                    }
                  }
                ]
              },
              {
                "type": "frame",
                "name": "Stack",
                "layout": {
                  "direction": "vertical",
                  "gap": 16,
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "frame",
                    "name": "Stack",
                    "layout": {
                      "direction": "vertical",
                      "gap": 6,
                      "width": "fill"
                    },
                    "style": {},
                    "children": [
                      {
                        "type": "text",
                        "name": "Email address",
                        "content": "Email address",
                        "style": {
                          "fontSize": 13,
                          "fontWeight": "medium",
                          "color": {
                            "r": 0.796078431372549,
                            "g": 0.8352941176470589,
                            "b": 0.8823529411764706,
                            "a": 1
                          }
                        }
                      },
                      {
                        "type": "frame",
                        "name": "Input / Email",
                        "layout": {
                          "direction": "horizontal",
                          "paddingRight": 16,
                          "paddingLeft": 16,
                          "alignItems": "center",
                          "width": "fill",
                          "height": 48
                        },
                        "style": {
                          "fill": {
                            "r": 0.08627450980392157,
                            "g": 0.09411764705882353,
                            "b": 0.10980392156862745,
                            "a": 1
                          },
                          "stroke": {
                            "r": 0.1843137254901961,
                            "g": 0.2,
                            "b": 0.21176470588235294,
                            "a": 1
                          },
                          "strokeWidth": 1,
                          "cornerRadius": 10
                        },
                        "children": [
                          {
                            "type": "text",
                            "name": "user@example.com",
                            "content": "user@example.com",
                            "style": {
                              "fontSize": 14,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Stack",
                    "layout": {
                      "direction": "vertical",
                      "gap": 6,
                      "width": "fill"
                    },
                    "style": {},
                    "children": [
                      {
                        "type": "text",
                        "name": "Password",
                        "content": "Password",
                        "style": {
                          "fontSize": 13,
                          "fontWeight": "medium",
                          "color": {
                            "r": 0.796078431372549,
                            "g": 0.8352941176470589,
                            "b": 0.8823529411764706,
                            "a": 1
                          }
                        }
                      },
                      {
                        "type": "frame",
                        "name": "Input / Password",
                        "layout": {
                          "direction": "horizontal",
                          "paddingRight": 16,
                          "paddingLeft": 16,
                          "alignItems": "center",
                          "width": "fill",
                          "height": 48
                        },
                        "style": {
                          "fill": {
                            "r": 0.08627450980392157,
                            "g": 0.09411764705882353,
                            "b": 0.10980392156862745,
                            "a": 1
                          },
                          "stroke": {
                            "r": 0.1843137254901961,
                            "g": 0.2,
                            "b": 0.21176470588235294,
                            "a": 1
                          },
                          "strokeWidth": 1,
                          "cornerRadius": 10
                        },
                        "children": [
                          {
                            "type": "text",
                            "name": "••••••••••••",
                            "content": "••••••••••••",
                            "style": {
                              "fontSize": 14,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "frame",
            "name": "Stack",
            "layout": {
              "direction": "vertical",
              "gap": 12,
              "width": "fill"
            },
            "style": {},
            "children": [
              {
                "type": "instance",
                "name": "ContinueButton",
                "componentName": "Button",
                "variant": "primary",
                "interaction": {
                  "trigger": "click",
                  "action": "navigate",
                  "destination": "Dashboard",
                  "transition": "smart-animate"
                },
                "overrides": {
                  "text": {
                    "label": "Continue to Dashboard"
                  },
                  "style": {
                    "fill": {
                      "r": 0.11372549019607843,
                      "g": 0.6078431372549019,
                      "b": 0.9411764705882353,
                      "a": 1
                    }
                  }
                },
                "layout": {
                  "direction": "horizontal",
                  "gap": 8,
                  "paddingTop": 12,
                  "paddingBottom": 12,
                  "paddingLeft": 24,
                  "paddingRight": 24,
                  "alignItems": "center",
                  "justifyContent": "center",
                  "width": "fill"
                }
              },
              {
                "type": "text",
                "name": "Protected by end-to-end ",
                "content": "Protected by end-to-end multi-layer encryption",
                "style": {
                  "fontSize": 13,
                  "color": {
                    "r": 0.39215686274509803,
                    "g": 0.4549019607843137,
                    "b": 0.5450980392156862,
                    "a": 1
                  },
                  "textAlign": "center"
                }
              }
            ]
          }
        ]
      }
    },
    {
      "id": "Dashboard",
      "name": "Dashboard Screen",
      "root": {
        "type": "frame",
        "id": "Dashboard",
        "name": "Dashboard",
        "layout": {
          "direction": "vertical",
          "paddingTop": 28,
          "paddingRight": 28,
          "paddingBottom": 28,
          "paddingLeft": 28,
          "justifyContent": "space-between",
          "width": 390,
          "height": 844
        },
        "style": {
          "fill": {
            "r": 0.0392156862745098,
            "g": 0.047058823529411764,
            "b": 0.058823529411764705,
            "a": 1
          }
        },
        "children": [
          {
            "type": "frame",
            "name": "Stack",
            "layout": {
              "direction": "vertical",
              "gap": 24,
              "width": "fill"
            },
            "style": {},
            "children": [
              {
                "type": "frame",
                "name": "Row",
                "layout": {
                  "direction": "horizontal",
                  "alignItems": "center",
                  "justifyContent": "space-between",
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "frame",
                    "name": "Stack",
                    "layout": {
                      "direction": "vertical",
                      "gap": 4
                    },
                    "style": {},
                    "children": [
                      {
                        "type": "text",
                        "name": "Welcome, Mohammed",
                        "content": "Welcome, Mohammed",
                        "style": {
                          "fontSize": 13,
                          "color": {
                            "r": 0.5803921568627451,
                            "g": 0.6392156862745098,
                            "b": 0.7215686274509804,
                            "a": 1
                          }
                        }
                      },
                      {
                        "type": "text",
                        "name": "Conversations",
                        "content": "Conversations",
                        "style": {
                          "fontSize": 26,
                          "fontWeight": "bold",
                          "color": {
                            "r": 1,
                            "g": 1,
                            "b": 1,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "rectangle",
                    "name": "Rectangle",
                    "width": 44,
                    "height": 44,
                    "style": {
                      "fill": {
                        "r": 0.11372549019607843,
                        "g": 0.6078431372549019,
                        "b": 0.9411764705882353,
                        "a": 1
                      },
                      "cornerRadius": 22
                    }
                  }
                ]
              },
              {
                "type": "frame",
                "name": "Row",
                "layout": {
                  "direction": "horizontal",
                  "gap": 12,
                  "alignItems": "center",
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "frame",
                    "name": "StatCard / Active",
                    "layout": {
                      "direction": "vertical",
                      "gap": 6,
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "text",
                        "name": "Active Chats",
                        "content": "Active Chats",
                        "style": {
                          "fontSize": 12,
                          "color": {
                            "r": 0.5803921568627451,
                            "g": 0.6392156862745098,
                            "b": 0.7215686274509804,
                            "a": 1
                          }
                        }
                      },
                      {
                        "type": "text",
                        "name": "18",
                        "content": "18",
                        "style": {
                          "fontSize": 24,
                          "fontWeight": "bold",
                          "color": {
                            "r": 1,
                            "g": 1,
                            "b": 1,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "StatCard / Unread",
                    "layout": {
                      "direction": "vertical",
                      "gap": 6,
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "text",
                        "name": "Unread Messages",
                        "content": "Unread Messages",
                        "style": {
                          "fontSize": 12,
                          "color": {
                            "r": 0.5803921568627451,
                            "g": 0.6392156862745098,
                            "b": 0.7215686274509804,
                            "a": 1
                          }
                        }
                      },
                      {
                        "type": "text",
                        "name": "4",
                        "content": "4",
                        "style": {
                          "fontSize": 24,
                          "fontWeight": "bold",
                          "color": {
                            "r": 0.11372549019607843,
                            "g": 0.6078431372549019,
                            "b": 0.9411764705882353,
                            "a": 1
                          }
                        }
                      }
                    ]
                  }
                ]
              },
              {
                "type": "frame",
                "name": "Stack",
                "layout": {
                  "direction": "vertical",
                  "gap": 10,
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "text",
                    "name": "Recent Channels",
                    "content": "Recent Channels",
                    "style": {
                      "fontSize": 15,
                      "fontWeight": "semibold",
                      "color": {
                        "r": 0.796078431372549,
                        "g": 0.8352941176470589,
                        "b": 0.8823529411764706,
                        "a": 1
                      }
                    }
                  },
                  {
                    "type": "frame",
                    "name": "Channel / Core Engineering",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 14,
                      "paddingRight": 14,
                      "paddingBottom": 14,
                      "paddingLeft": 14,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "cornerRadius": 12
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Row",
                        "layout": {
                          "direction": "horizontal",
                          "gap": 12,
                          "alignItems": "center"
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "rectangle",
                            "name": "Rectangle",
                            "width": 32,
                            "height": 32,
                            "style": {
                              "fill": {
                                "r": 0.15294117647058825,
                                "g": 0.15294117647058825,
                                "b": 0.16470588235294117,
                                "a": 1
                              },
                              "cornerRadius": 8
                            }
                          },
                          {
                            "type": "frame",
                            "name": "Stack",
                            "layout": {
                              "direction": "vertical",
                              "gap": 2
                            },
                            "style": {},
                            "children": [
                              {
                                "type": "text",
                                "name": "Core Engineering",
                                "content": "Core Engineering",
                                "style": {
                                  "fontSize": 14,
                                  "fontWeight": "medium",
                                  "color": {
                                    "r": 1,
                                    "g": 1,
                                    "b": 1,
                                    "a": 1
                                  }
                                }
                              },
                              {
                                "type": "text",
                                "name": "Latest update 5m ago",
                                "content": "Latest update 5m ago",
                                "style": {
                                  "fontSize": 12,
                                  "color": {
                                    "r": 0.39215686274509803,
                                    "g": 0.4549019607843137,
                                    "b": 0.5450980392156862,
                                    "a": 1
                                  }
                                }
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "Active",
                        "content": "Active",
                        "style": {
                          "fontSize": 12,
                          "color": {
                            "r": 0.11372549019607843,
                            "g": 0.6078431372549019,
                            "b": 0.9411764705882353,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Channel / Design Systems",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 14,
                      "paddingRight": 14,
                      "paddingBottom": 14,
                      "paddingLeft": 14,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "cornerRadius": 12
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Row",
                        "layout": {
                          "direction": "horizontal",
                          "gap": 12,
                          "alignItems": "center"
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "rectangle",
                            "name": "Rectangle",
                            "width": 32,
                            "height": 32,
                            "style": {
                              "fill": {
                                "r": 0.15294117647058825,
                                "g": 0.15294117647058825,
                                "b": 0.16470588235294117,
                                "a": 1
                              },
                              "cornerRadius": 8
                            }
                          },
                          {
                            "type": "frame",
                            "name": "Stack",
                            "layout": {
                              "direction": "vertical",
                              "gap": 2
                            },
                            "style": {},
                            "children": [
                              {
                                "type": "text",
                                "name": "Design Systems",
                                "content": "Design Systems",
                                "style": {
                                  "fontSize": 14,
                                  "fontWeight": "medium",
                                  "color": {
                                    "r": 1,
                                    "g": 1,
                                    "b": 1,
                                    "a": 1
                                  }
                                }
                              },
                              {
                                "type": "text",
                                "name": "Latest update 5m ago",
                                "content": "Latest update 5m ago",
                                "style": {
                                  "fontSize": 12,
                                  "color": {
                                    "r": 0.39215686274509803,
                                    "g": 0.4549019607843137,
                                    "b": 0.5450980392156862,
                                    "a": 1
                                  }
                                }
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "Active",
                        "content": "Active",
                        "style": {
                          "fontSize": 12,
                          "color": {
                            "r": 0.11372549019607843,
                            "g": 0.6078431372549019,
                            "b": 0.9411764705882353,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Channel / Product Announcements",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 14,
                      "paddingRight": 14,
                      "paddingBottom": 14,
                      "paddingLeft": 14,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "cornerRadius": 12
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Row",
                        "layout": {
                          "direction": "horizontal",
                          "gap": 12,
                          "alignItems": "center"
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "rectangle",
                            "name": "Rectangle",
                            "width": 32,
                            "height": 32,
                            "style": {
                              "fill": {
                                "r": 0.15294117647058825,
                                "g": 0.15294117647058825,
                                "b": 0.16470588235294117,
                                "a": 1
                              },
                              "cornerRadius": 8
                            }
                          },
                          {
                            "type": "frame",
                            "name": "Stack",
                            "layout": {
                              "direction": "vertical",
                              "gap": 2
                            },
                            "style": {},
                            "children": [
                              {
                                "type": "text",
                                "name": "Product Announcements",
                                "content": "Product Announcements",
                                "style": {
                                  "fontSize": 14,
                                  "fontWeight": "medium",
                                  "color": {
                                    "r": 1,
                                    "g": 1,
                                    "b": 1,
                                    "a": 1
                                  }
                                }
                              },
                              {
                                "type": "text",
                                "name": "Latest update 5m ago",
                                "content": "Latest update 5m ago",
                                "style": {
                                  "fontSize": 12,
                                  "color": {
                                    "r": 0.39215686274509803,
                                    "g": 0.4549019607843137,
                                    "b": 0.5450980392156862,
                                    "a": 1
                                  }
                                }
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "Active",
                        "content": "Active",
                        "style": {
                          "fontSize": 12,
                          "color": {
                            "r": 0.11372549019607843,
                            "g": 0.6078431372549019,
                            "b": 0.9411764705882353,
                            "a": 1
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "frame",
            "name": "Stack",
            "layout": {
              "direction": "vertical",
              "gap": 12,
              "width": "fill"
            },
            "style": {},
            "children": [
              {
                "type": "instance",
                "name": "OpenSettingsButton",
                "componentName": "Button",
                "variant": "secondary",
                "interaction": {
                  "trigger": "click",
                  "action": "navigate",
                  "destination": "Settings",
                  "transition": "smart-animate"
                },
                "overrides": {
                  "text": {
                    "label": "Open Settings"
                  },
                  "style": {
                    "fill": {
                      "r": 0.15294117647058825,
                      "g": 0.15294117647058825,
                      "b": 0.16470588235294117,
                      "a": 1
                    }
                  }
                },
                "layout": {
                  "direction": "horizontal",
                  "gap": 8,
                  "paddingTop": 12,
                  "paddingBottom": 12,
                  "paddingLeft": 24,
                  "paddingRight": 24,
                  "alignItems": "center",
                  "justifyContent": "center",
                  "width": "fill"
                }
              },
              {
                "type": "instance",
                "name": "SignOutButton",
                "componentName": "Button",
                "variant": "outline",
                "interaction": {
                  "trigger": "click",
                  "action": "navigate",
                  "destination": "Login",
                  "transition": "smart-animate"
                },
                "overrides": {
                  "text": {
                    "label": "Back to Login"
                  },
                  "style": {
                    "fill": {
                      "r": 0,
                      "g": 0,
                      "b": 0,
                      "a": 0
                    }
                  }
                },
                "layout": {
                  "direction": "horizontal",
                  "gap": 8,
                  "paddingTop": 12,
                  "paddingBottom": 12,
                  "paddingLeft": 24,
                  "paddingRight": 24,
                  "alignItems": "center",
                  "justifyContent": "center",
                  "width": "fill"
                }
              }
            ]
          }
        ]
      }
    },
    {
      "id": "Settings",
      "name": "Settings Screen",
      "root": {
        "type": "frame",
        "id": "Settings",
        "name": "Settings",
        "layout": {
          "direction": "vertical",
          "paddingTop": 28,
          "paddingRight": 28,
          "paddingBottom": 28,
          "paddingLeft": 28,
          "justifyContent": "space-between",
          "width": 390,
          "height": 844
        },
        "style": {
          "fill": {
            "r": 0.0392156862745098,
            "g": 0.047058823529411764,
            "b": 0.058823529411764705,
            "a": 1
          }
        },
        "children": [
          {
            "type": "frame",
            "name": "Stack",
            "layout": {
              "direction": "vertical",
              "gap": 24,
              "width": "fill"
            },
            "style": {},
            "children": [
              {
                "type": "frame",
                "name": "Row",
                "layout": {
                  "direction": "horizontal",
                  "gap": 12,
                  "alignItems": "center",
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "instance",
                    "name": "BackButton",
                    "componentName": "Button",
                    "variant": "secondary",
                    "interaction": {
                      "trigger": "click",
                      "action": "navigate",
                      "destination": "Dashboard",
                      "transition": "smart-animate"
                    },
                    "overrides": {
                      "text": {
                        "label": "← Back"
                      },
                      "style": {
                        "fill": {
                          "r": 0.15294117647058825,
                          "g": 0.15294117647058825,
                          "b": 0.16470588235294117,
                          "a": 1
                        }
                      }
                    },
                    "layout": {
                      "direction": "horizontal",
                      "gap": 8,
                      "paddingTop": 12,
                      "paddingBottom": 12,
                      "paddingLeft": 24,
                      "paddingRight": 24,
                      "alignItems": "center",
                      "justifyContent": "center",
                      "width": "hug"
                    }
                  },
                  {
                    "type": "text",
                    "name": "Settings",
                    "content": "Settings",
                    "style": {
                      "fontSize": 22,
                      "fontWeight": "bold",
                      "color": {
                        "r": 1,
                        "g": 1,
                        "b": 1,
                        "a": 1
                      }
                    }
                  }
                ]
              },
              {
                "type": "frame",
                "name": "Stack",
                "layout": {
                  "direction": "vertical",
                  "gap": 12,
                  "width": "fill"
                },
                "style": {},
                "children": [
                  {
                    "type": "frame",
                    "name": "Setting / Privacy & Security",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Stack",
                        "layout": {
                          "direction": "vertical",
                          "gap": 3
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "text",
                            "name": "Privacy & Security",
                            "content": "Privacy & Security",
                            "style": {
                              "fontSize": 15,
                              "fontWeight": "medium",
                              "color": {
                                "r": 1,
                                "g": 1,
                                "b": 1,
                                "a": 1
                              }
                            }
                          },
                          {
                            "type": "text",
                            "name": "Manage encryption keys a",
                            "content": "Manage encryption keys and active sessions",
                            "style": {
                              "fontSize": 12,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "›",
                        "content": "›",
                        "style": {
                          "fontSize": 16,
                          "color": {
                            "r": 0.39215686274509803,
                            "g": 0.4549019607843137,
                            "b": 0.5450980392156862,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Setting / Notifications",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Stack",
                        "layout": {
                          "direction": "vertical",
                          "gap": 3
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "text",
                            "name": "Notifications",
                            "content": "Notifications",
                            "style": {
                              "fontSize": 15,
                              "fontWeight": "medium",
                              "color": {
                                "r": 1,
                                "g": 1,
                                "b": 1,
                                "a": 1
                              }
                            }
                          },
                          {
                            "type": "text",
                            "name": "Configure instant push a",
                            "content": "Configure instant push alerts and sound triggers",
                            "style": {
                              "fontSize": 12,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "›",
                        "content": "›",
                        "style": {
                          "fontSize": 16,
                          "color": {
                            "r": 0.39215686274509803,
                            "g": 0.4549019607843137,
                            "b": 0.5450980392156862,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Setting / Theme & Appearance",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Stack",
                        "layout": {
                          "direction": "vertical",
                          "gap": 3
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "text",
                            "name": "Theme & Appearance",
                            "content": "Theme & Appearance",
                            "style": {
                              "fontSize": 15,
                              "fontWeight": "medium",
                              "color": {
                                "r": 1,
                                "g": 1,
                                "b": 1,
                                "a": 1
                              }
                            }
                          },
                          {
                            "type": "text",
                            "name": "Dark theme, typography a",
                            "content": "Dark theme, typography and display density",
                            "style": {
                              "fontSize": 12,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "›",
                        "content": "›",
                        "style": {
                          "fontSize": 16,
                          "color": {
                            "r": 0.39215686274509803,
                            "g": 0.4549019607843137,
                            "b": 0.5450980392156862,
                            "a": 1
                          }
                        }
                      }
                    ]
                  },
                  {
                    "type": "frame",
                    "name": "Setting / Connected Devices",
                    "layout": {
                      "direction": "horizontal",
                      "paddingTop": 16,
                      "paddingRight": 16,
                      "paddingBottom": 16,
                      "paddingLeft": 16,
                      "alignItems": "center",
                      "justifyContent": "space-between",
                      "width": "fill"
                    },
                    "style": {
                      "fill": {
                        "r": 0.08627450980392157,
                        "g": 0.09411764705882353,
                        "b": 0.10980392156862745,
                        "a": 1
                      },
                      "stroke": {
                        "r": 0.1843137254901961,
                        "g": 0.2,
                        "b": 0.21176470588235294,
                        "a": 1
                      },
                      "strokeWidth": 1,
                      "cornerRadius": 14
                    },
                    "children": [
                      {
                        "type": "frame",
                        "name": "Stack",
                        "layout": {
                          "direction": "vertical",
                          "gap": 3
                        },
                        "style": {},
                        "children": [
                          {
                            "type": "text",
                            "name": "Connected Devices",
                            "content": "Connected Devices",
                            "style": {
                              "fontSize": 15,
                              "fontWeight": "medium",
                              "color": {
                                "r": 1,
                                "g": 1,
                                "b": 1,
                                "a": 1
                              }
                            }
                          },
                          {
                            "type": "text",
                            "name": "Manage 3 active linked d",
                            "content": "Manage 3 active linked devices",
                            "style": {
                              "fontSize": 12,
                              "color": {
                                "r": 0.39215686274509803,
                                "g": 0.4549019607843137,
                                "b": 0.5450980392156862,
                                "a": 1
                              }
                            }
                          }
                        ]
                      },
                      {
                        "type": "text",
                        "name": "›",
                        "content": "›",
                        "style": {
                          "fontSize": 16,
                          "color": {
                            "r": 0.39215686274509803,
                            "g": 0.4549019607843137,
                            "b": 0.5450980392156862,
                            "a": 1
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "instance",
            "name": "SaveButton",
            "componentName": "Button",
            "variant": "primary",
            "interaction": {
              "trigger": "click",
              "action": "navigate",
              "destination": "Dashboard",
              "transition": "smart-animate"
            },
            "overrides": {
              "text": {
                "label": "Save & Return to Dashboard"
              },
              "style": {
                "fill": {
                  "r": 0.11372549019607843,
                  "g": 0.6078431372549019,
                  "b": 0.9411764705882353,
                  "a": 1
                }
              }
            },
            "layout": {
              "direction": "horizontal",
              "gap": 8,
              "paddingTop": 12,
              "paddingBottom": 12,
              "paddingLeft": 24,
              "paddingRight": 24,
              "alignItems": "center",
              "justifyContent": "center",
              "width": "fill"
            }
          }
        ]
      }
    }
  ]
};

function hexToRgb(h) {
  const clean = h.replace('#', '');
  if (clean.length === 3) {
    return {
      r: parseInt(clean[0] + clean[0], 16) / 255,
      g: parseInt(clean[1] + clean[1], 16) / 255,
      b: parseInt(clean[2] + clean[2], 16) / 255
    };
  }
  return {
    r: parseInt(clean.slice(0, 2), 16) / 255,
    g: parseInt(clean.slice(2, 4), 16) / 255,
    b: parseInt(clean.slice(4, 6), 16) / 255
  };
}

function toFigmaPaint(color) {
  if (!color) return [];
  if (typeof color === 'string') {
    return [{ type: 'SOLID', color: hexToRgb(color) }];
  }
  return [{
    type: 'SOLID',
    color: { r: color.r, g: color.g, b: color.b },
    opacity: color.a !== undefined ? color.a : 1
  }];
}

async function loadFonts() {
  const fonts = [
    { family: 'Inter', style: 'Regular' },
    { family: 'Inter', style: 'Medium' },
    { family: 'Inter', style: 'Semi Bold' },
    { family: 'Inter', style: 'Bold' },
    { family: 'Roboto', style: 'Regular' },
    { family: 'Roboto', style: 'Bold' }
  ];

  for (const f of fonts) {
    try {
      await figma.loadFontAsync(f);
    } catch (e) {}
  }
}

function applyLayout(node, layout) {
  if (!layout) {
    node.layoutMode = 'NONE';
    return;
  }

  if (layout.direction === 'vertical') {
    node.layoutMode = 'VERTICAL';
  } else if (layout.direction === 'horizontal') {
    node.layoutMode = 'HORIZONTAL';
  } else {
    node.layoutMode = 'NONE';
  }

  if (node.layoutMode !== 'NONE') {
    node.itemSpacing = layout.gap || 0;
    node.paddingTop = layout.paddingTop || 0;
    node.paddingRight = layout.paddingRight || 0;
    node.paddingBottom = layout.paddingBottom || 0;
    node.paddingLeft = layout.paddingLeft || 0;

    if (layout.alignItems === 'start') node.counterAxisAlignItems = 'MIN';
    else if (layout.alignItems === 'center') node.counterAxisAlignItems = 'CENTER';
    else if (layout.alignItems === 'end') node.counterAxisAlignItems = 'MAX';

    if (layout.justifyContent === 'start') node.primaryAxisAlignItems = 'MIN';
    else if (layout.justifyContent === 'center') node.primaryAxisAlignItems = 'CENTER';
    else if (layout.justifyContent === 'end') node.primaryAxisAlignItems = 'MAX';
    else if (layout.justifyContent === 'space-between') node.primaryAxisAlignItems = 'SPACE_BETWEEN';

    if (layout.width === 'fill') {
      try { node.layoutSizingHorizontal = 'FILL'; node.layoutGrow = 1; } catch (e) {}
    } else if (layout.width === 'hug') {
      try { node.layoutSizingHorizontal = 'HUG'; } catch (e) {}
    } else if (typeof layout.width === 'number') {
      node.resize(layout.width, node.height || 40);
    }

    if (layout.height === 'fill') {
      try { node.layoutSizingVertical = 'FILL'; } catch (e) {}
    } else if (layout.height === 'hug') {
      try { node.layoutSizingVertical = 'HUG'; } catch (e) {}
    } else if (typeof layout.height === 'number') {
      node.resize(node.width || 40, layout.height);
    }
  } else {
    const w = typeof layout.width === 'number' ? layout.width : node.width;
    const h = typeof layout.height === 'number' ? layout.height : node.height;
    node.resize(w, h);
  }
}

function applyStyle(node, style) {
  if (!style) return;
  if (style.fill) node.fills = toFigmaPaint(style.fill);
  if (style.stroke) {
    node.strokes = toFigmaPaint(style.stroke);
    node.strokeWeight = style.strokeWidth || 1;
  }
  if (style.cornerRadius !== undefined) {
    node.cornerRadius = Array.isArray(style.cornerRadius) ? style.cornerRadius[0] : style.cornerRadius;
  }
  if (style.opacity !== undefined) node.opacity = style.opacity;
}

const componentRegistry = new Map();
const screenRegistry = new Map();
const interactiveNodes = [];

async function renderIRNode(ir) {
  let figmaNode;

  switch (ir.type) {
    case 'frame': {
      const f = figma.createFrame();
      f.name = ir.name || 'Frame';
      applyLayout(f, ir.layout);
      applyStyle(f, ir.style);

      if (ir.children) {
        for (const childIR of ir.children) {
          const childNode = await renderIRNode(childIR);
          f.appendChild(childNode);
        }
      }
      figmaNode = f;
      break;
    }

    case 'text': {
      const t = figma.createText();
      t.name = ir.name || ir.content.slice(0, 20);
      try {
        const style = ir.style && (ir.style.fontWeight === 'bold' || ir.style.fontWeight >= 700) ? 'Bold' : 'Regular';
        t.fontName = { family: 'Inter', style };
      } catch (e) {
        t.fontName = { family: 'Roboto', style: 'Regular' };
      }
      t.characters = ir.content || '';
      if (ir.style && ir.style.fontSize) t.fontSize = ir.style.fontSize;
      if (ir.style && ir.style.color) t.fills = toFigmaPaint(ir.style.color);
      figmaNode = t;
      break;
    }

    case 'rectangle': {
      const r = figma.createRectangle();
      r.name = ir.name || 'Rectangle';
      const w = typeof ir.width === 'number' ? ir.width : 100;
      const h = typeof ir.height === 'number' ? ir.height : 100;
      r.resize(w, h);
      applyStyle(r, ir.style);
      figmaNode = r;
      break;
    }

    case 'component': {
      const c = figma.createComponent();
      c.name = ir.name || ir.componentName;
      applyLayout(c, ir.layout);
      applyStyle(c, ir.style);
      if (ir.children) {
        for (const childIR of ir.children) {
          const child = await renderIRNode(childIR);
          c.appendChild(child);
        }
      }
      componentRegistry.set(ir.componentName, c);
      figmaNode = c;
      break;
    }

    case 'instance': {
      const mainComp = componentRegistry.get(ir.componentName);
      if (mainComp) {
        const inst = mainComp.createInstance();
        inst.name = ir.name || mainComp.name;
        if (ir.layout) applyLayout(inst, ir.layout);
        if (ir.overrides && ir.overrides.style) applyStyle(inst, ir.overrides.style);
        figmaNode = inst;
      } else {
        const placeholder = figma.createFrame();
        placeholder.name = ir.name || ir.componentName;
        applyLayout(placeholder, ir.layout);
        figmaNode = placeholder;
      }
      break;
    }
  }

  if (ir.interaction && figmaNode) {
    interactiveNodes.push({ node: figmaNode, interaction: ir.interaction, name: ir.name });
  }

  return figmaNode;
}

async function run() {
  await loadFonts();

  const page = figma.createPage();
  page.name = appDefinition.name;

  // 1. Render reusable components
  if (appDefinition.components) {
    let cx = 0;
    for (const compIR of appDefinition.components) {
      const c = await renderIRNode(compIR);
      c.x = cx;
      c.y = -220;
      page.appendChild(c);
      cx += c.width + 40;
    }
  }

  // 2. Render screens
  const screenFrames = [];
  let sx = 0;
  for (const screenDef of appDefinition.screens) {
    const screenFrame = await renderIRNode(screenDef.root);
    screenFrame.name = screenDef.name;
    screenFrame.x = sx;
    screenFrame.y = 0;
    page.appendChild(screenFrame);

    screenRegistry.set(screenDef.id.toLowerCase(), screenFrame);
    screenRegistry.set(screenDef.name.toLowerCase(), screenFrame);
    screenFrames.push(screenFrame);
    sx += screenFrame.width + 120;
  }

  // 3. Resolve Prototype Connections (Phase 7 & 8)
  for (const item of interactiveNodes) {
    if (item.interaction && item.interaction.destination) {
      const dest = screenRegistry.get(item.interaction.destination.toLowerCase());
      if (dest) {
        try {
          item.node.reactions = [{
            trigger: { type: item.interaction.trigger === 'hover' ? 'ON_HOVER' : 'ON_CLICK' },
            action: {
              type: 'NODE',
              destinationId: dest.id,
              navigation: item.interaction.action === 'open-overlay' ? 'OVERLAY' : 'NAVIGATE',
              transition: {
                type: item.interaction.transition === 'instant' ? 'INSTANT' : 'SMART_ANIMATE',
                duration: 0.3,
                easing: { type: 'EASE_IN_AND_OUT' }
              }
            }
          }];
        } catch (e) {
          console.warn('Could not set reactions on node:', item.name, e);
        }
      }
    }
  }

  figma.currentPage = page;
  figma.viewport.scrollAndZoomIntoView(screenFrames);
  figma.closePlugin('Generated ' + screenFrames.length + ' screens with editable Auto Layout and prototype connections');
}

run().catch((e) => {
  figma.closePlugin('Error: ' + ((e && e.message) || String(e)));
});
